# Generated by Django 6.0.4 on 2026-04-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_user_user_id_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
