# Generated by Django 6.0.4 on 2026-04-30 10:20

from django.db import migrations

# creates admin when migrating
def create_admin(apps, schema_editor):
    User = apps.get_model('register','User')
    User.objects.create_superuser(
        username="admin1",
        email="admin1@gmail.com",
        password="admin1",
        first_name="admin1",
        last_name="admin1",
        is_staff=True,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_user_user_id'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]
