# Generated by Django 6.0.4 on 2026-04-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_userrequest_delete_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='user_request_id',
            new_name='request_id',
        ),
    ]
