# Generated by Django 6.0.4 on 2026-04-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_rename_user_request_id_userrequest_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='request_id',
        ),
    ]
